### ISSUE TITLE
Run without Docker

### ISSUE THREAD

**Issue by fakerybakery** [devidw/dswav#5]
Hi,
Amazing project. Is there any possibility of running this without Docker? Should I just install whisper and poetry, and run `__main__.py`?
Thank you!

**Comment by devidw** [comment]
Hey @fakerybakery 

Yeah

Just make sure you have those os deps

- ffmpeg
- espeak

Along with whisper cli on your PATH, can install with pip

To set up the python deps you need poetry, then `poetry install`

Then you can enter the poetry virtual env and start the service with `python -m dswav`

**Comment by fakerybakery** [comment]
OK, makes sense. Thank you!
